# Generated by Django 3.2.3 on 2021-05-25 13:18

import cloudinary.models
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_photo', cloudinary.models.CloudinaryField(default=None, max_length=255, verbose_name='image')),
                ('bio', models.TextField()),
                ('user_name', models.CharField(max_length=255)),
                ('followers', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('following', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(default=None, max_length=255, verbose_name='image')),
                ('image_name', models.CharField(max_length=255)),
                ('image_caption', models.CharField(max_length=255)),
                ('likes', models.IntegerField()),
                ('profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='image.profile')),
            ],
        ),
    ]
