# Generated by Django 3.2.3 on 2021-05-26 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0002_auto_20210526_0028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='profile',
        ),
        migrations.AddField(
            model_name='comment',
            name='image_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='image.image'),
            preserve_default=False,
        ),
    ]
